### PR TITLE
A1 map loader pr

### LINKED ISSUE #4: Part 2: Map loader
### Acceptance Criteria
- Map loader can read the eight-minute empire Legends map file.
- Map loader creates a map object as a graph data structure (see Part 1). 
- Map loader should be able to read any map file format (e.g text) (even invalid ones). 
- Driver reads many different map files, creates a graph object for the valid ones and rejects the invalid ones. 

### Epic Description

Implement a group of C++ classes that reads and loads a map file, that contains the four game boards of the eight-minute empire Legends game. The map loader must be able to read any map file, that is any file characterizing any of the four game’s board. The map loader should store the map as a graph data structure (see Part 1). The map loader should be able to read any map file format (even ones that do not constitute a valid map). All the classes/functions that you implement for this component must all reside in a single .cpp/.h file duo named MapLoader.cpp/MapLoader.h. You must deliver a file named  MapLoaderDriver.cpp file that contains a main function that reads various files and successfully creates a map object for valid map files, and rejects invalid map files of different kinds.

### PR DESCRIPTION
**Pull request by joshpham97**
Refactor A1-Maploader branch to remove all commits for Map.

### CODE REVIEW

**Comment by joshpham97** [comment]
Apparently, because you guys did not merge the code for the Map branch into the main branch, and my branch depends on the Map branch, so it looks like I'm pushing the Map files. Please merge the Map branch first. I did not make ANY changes in the Map.ccp/h.

**Review by jaforte — CHANGES_REQUESTED** [review]
Everything looks good, but to avoid merge conflicts please remove all Map files from this branch.

**Comment by joshpham97** [comment]
I can't because my branch depends on yours so unless your branch is merged i cannot remove the map files.

**Comment by joshpham97** [comment]
Closing this PR to make sure that no map files are pushed (again).

**Pull request closed without merging**
