### PR TITLE
added gitignore and tested it with hello world project

### LINKED ISSUE #9: Create Visual Studio solution
Create solution and file structure for assignment 1.

### PR DESCRIPTION
**Pull request by jonZlotnik**
Created a solution with a Hello World project to test the .gitignore from gitignore.io

@jaforte , you can use this solution if you want and adjust the settings and projects how you want.

### CODE REVIEW

**Review by jaforte — DISMISSED** [review]

**Comment by jaforte** [comment]
Looks good but I'd like to retain the file structure VS 2019 creates for empty C++ projects, so each project in the solution will have a header files folder and source files folder, etc.

EDIT: Nvm, I didn't click on the .sln file. I see the file structure is good.

**Comment by jonZlotnik** [comment]
> Looks good but I'd like to retain the file structure VS 2019 creates for empty C++ projects, so each project in the solution will have a header files folder and source files folder, etc.
> 
> EDIT: Nvm, I didn't click on the .sln file. I see the file structure is good.

Those aren't actually folders. They're just filters for you to see them in the VS solution explorer

**Comment by jonZlotnik** [comment]
@jaforte I don't think you saved the solution file after adding the projects, so they didn't come up when I opened the solution. I added them just now in [c5c25e8](https://github.com/COMP-345-Team-Project/eight-minute-empire-legends/pull/10/commits/c5c25e886c5b027c966835e374830574c6fca8ab)

**Comment by jaforte** [comment]
> > Looks good but I'd like to retain the file structure VS 2019 creates for empty C++ projects, so each project in the solution will have a header files folder and source files folder, etc.
> > EDIT: Nvm, I didn't click on the .sln file. I see the file structure is good.
> 
> Those aren't actually folders. They're just filters for you to see them in the VS solution explorer

Ah I understand. Thanks!

**Review by joshpham97 — APPROVED** [review]

**Pull request merged**
